
version: '2'

services:
  itest:
    build: .
    links:
      - kafka
      - zookeeper
    volumes:
      - .:/mount
    command: ./run_tests.sh

  kafka:
    build: docker/kafka_1.0.2
    logging:
      driver: none  # Hide output
    expose:
      - "9092"
    links:
      - zookeeper

  zookeeper:
    build: docker/zookeeper
    logging:
      driver: none  # Hide output
    expose:
      - "2181"