[package]
name = "rdkafka-sys"
version = "0.11.6-1"
authors = ["Federico Giraud <giraud.federico@gmail.com>"]
build = "build.rs"
links = "rdkafka"
repository = "https://github.com/fede1024/rust-rdkafka"
license = "MIT"
description = "Native bindings to the librdkafka library"
keywords = ["kafka", "rdkafka"]
categories = ["external-ffi-bindings"]

[profile.debug]
opt-level        = 3
debug            = true
rpath            = false
lto              = 'thin'
debug-assertions = false
codegen-units    = 1
panic            = 'unwind'
incremental      = false
overflow-checks  = false

[profile.release]
debug            = true
rpath            = false
lto              = 'thin'
debug-assertions = false
codegen-units    = 1
panic            = 'unwind'
incremental      = false
overflow-checks  = false

[dependencies]
libz-sys = "1.0"
openssl-sys = { version = "~ 0.9.0", optional = true }

[build-dependencies]
num_cpus = "0.2.0"
pkg-config = "0.3.9"
cmake = { version = "^0.1", optional = true }

[lib]
name = "rdkafka_sys"
path = "src/lib.rs"

[features]
default = []

# Enable ssl and sasl support
ssl = ["openssl-sys"]
sasl = ["ssl"]

# Use dynamic linking instead of static. Will fail if librdkafka is not installed.
dynamic_linking = []

# Use external library for lz4. Use internal if not enabled.
external_lz4 = []

cmake_build = ["cmake"]
